window['switStrings'] = {
	"STR_LOADING_PRELOAD_FONT_4": {"value": "0", "locID": ""},
	"STR_LOADING_PRELOAD_FONT_3": {"value": "0", "locID": ""},
	"STR_LOADING_PRELOAD_FONT_2": {"value": "0", "locID": ""},
	"STR_LOADING_PRELOAD_FONT_1": {"value": "0", "locID": ""},
	"STR_MAINMENU_SELECTMODE": {"value": "SELECT MODE", "locID": ""},
	"STR_MAINMENU_GAMENAME": {"value": "GAME NAME", "locID": ""},
	"STR_REP_HUD_TIMER": {"value": "#", "locID": ""},
	"STR_MAINMENU_STORY": {"value": "STORY", "locID": ""},
	"STR_MAINMENU_CHALLENGE": {"value": "CHALLENGE", "locID": ""},
	"STR_MAINMENU_CHALLENGE_S": {"value": "CHALLENGE", "locID": "STR_MAINMENU_CHALLENGE"},
	"STR_CONTINUE_TITLE": {"value": "CONTINUE", "locID": ""},
	"STR_CONTINUE_DESCRIPTION": {"value": "Resume last fight?", "locID": ""},
	"STR_MAINMENU_TUTORIAL": {"value": "TUTORIAL", "locID": ""},
	"STR_MAINMENU_VERSUS": {"value": "BATTLE", "locID": ""},
	"STR_ANIMATION_TITLE_CRICKET": {"value": "CRICKET ANIMATIONS", "locID": ""},
	"STR_ANIMATION_TITLE_TILLY": {"value": "TILLY ANIMATIONS", "locID": ""},
	"STR_TRAINING_TITLE": {"value": "TRAINING", "locID": ""},
	"STR_TRAINING_DESCRIPTION": {"value": "Play the tutorial?", "locID": ""},
	"STR_PAUSE_TITLE": {"value": "PAUSE", "locID": ""},
	"STR_RESET_TITLE": {"value": "RESET ", "locID": ""},
	"STR_RESET_DESCRIPTION": {"value": "Delete all data?", "locID": ""},
	"STR_CONFIRM_TITLE": {"value": "QUIT", "locID": ""},
	"STR_CONFIRM_DESCRIPTION": {"value": "Are you sure?", "locID": ""},
	"STR_QUIT_TITLE": {"value": "QUIT GAME?", "locID": ""},
	"STR_CUTSCENE_CHARACTERNAME": {"value": "CHARACTER NAME", "locID": ""},
	"STR_CUTSCENE_CHARACTERDIALOG": {"value": "Today’s the day for you to become an official Green! ", "locID": ""},
	"STR_CUTSCENE_DIALOG_CRICKET_01_01": {"value": "Today’s the day for you to become an official Green! ", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_01_02": {"value": "For generations, members of the Green family have defeated the roughest, toughest, most vicious animal around as a rite of passage! ", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_01_03": {"value": "You bet yer britches! Bring it on!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_01_04": {"value": "So, do you think you got what it takes to become an official Green?!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_02_01": {"value": "This family rite of passage is impossible, Gramma!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_02_02": {"value": "Unless… the most vicious animal around has been in front of me this whole time…", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_02_03": {"value": "It's YOU, Gramma! I challenge YOU to fight me for the Green family name!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_02_04": {"value": "Hehehe… Very well. I accept your challenge!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_02_05": {"value": "What? No way. Cricket you're not gonna fight yer Gramma…", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_CRICKET_02_06": {"value": "Try and stop me, Dad!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_01_01": {"value": "Today’s the day for you to become an official Green! ", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_01_02": {"value": "For generations, members of the Green family have defeated the roughest, toughest, most vicious animal around as a rite of passage! ", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_01_03": {"value": "Yes. Yes I do.", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_01_04": {"value": "So, do you think you got what it takes to become an official Green?!", "locID": ""},
	"STR_CUTSCENE_DIALOG_TILLY_02_01": {"value": "It seems this city does not contain an animal worthy of your high standards, Gramma...", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_02_02": {"value": "Unless… the city's most vicious animal has been in front of me this whole time!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_02_03": {"value": "Gramma? Prepare to battle", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_02_04": {"value": "Hehehe… Very well. I accept your challenge!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_02_05": {"value": "What? No way! No one is fighting in this family!", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_CUTSCENE_DIALOG_TILLY_02_06": {"value": "Sorry Papa, but you cannot stop me.", "locID": "STR_CUTSCENE_DIALOG_CRICKET_01_01"},
	"STR_REP_SELECT_CHARACTER_READY_1": {"value": "READY", "locID": ""},
	"STR_REP_SELECT_CHARACTER_READY_1S": {"value": "READY", "locID": "STR_REP_SELECT_CHARACTER_READY_1"},
	"STR_REP_SELECT_CHARACTER_READY_2": {"value": "READY", "locID": "STR_REP_SELECT_CHARACTER_READY_1"},
	"STR_REP_SELECT_CHARACTER_READY_2S": {"value": "READY", "locID": "STR_REP_SELECT_CHARACTER_READY_1"},
	"STR_VSMODE_TITLE": {"value": "BATTLE MODE", "locID": ""},
	"STR_VSMODE_PLAYER": {"value": "PLAYER", "locID": ""},
	"STR_VSMODE_CPU": {"value": "COMPUTER", "locID": ""},
	"STR_LOADING_PERCENT": {"value": "#%", "locID": ""},
	"STR_REP_VS_CHARACTERNAME_1": {"value": "CHARACTER 1", "locID": ""},
	"STR_REP_VS_CHARACTERNAME_1S": {"value": "CHARACTER 1", "locID": "STR_REP_VS_CHARACTERNAME_1"},
	"STR_REP_VS_CHARACTERNAME_2": {"value": "CHARACTER 2", "locID": ""},
	"STR_REP_VS_CHARACTERNAME_2S": {"value": "CHARACTER 2", "locID": "STR_REP_VS_CHARACTERNAME_2"},
	"STR_SELECTCHARACTER_TITLE": {"value": "SELECT CHARACTER", "locID": ""},
	"STR_REP_STORY_CHARACTERNAME_1": {"value": "CRICKET", "locID": ""},
	"STR_REP_STORY_CHARACTERNAME_1S": {"value": "CRICKET", "locID": "STR_REP_STORY_CHARACTERNAME_1"},
	"STR_REP_STORY_CHARACTERNAME_2": {"value": "TILLY", "locID": ""},
	"STR_REP_STORY_CHARACTERNAME_2S": {"value": "TILLY", "locID": "STR_REP_STORY_CHARACTERNAME_2"},
	"STR_REP_VERSUS_PLAYER1": {"value": "PLAYER 1", "locID": ""},
	"STR_REP_VERSUS_PLAYER1_S": {"value": "PLAYER 1", "locID": "STR_REP_VERSUS_PLAYER1"},
	"STR_REP_VERSUS_PLAYER2": {"value": "PLAYER 2", "locID": ""},
	"STR_REP_VERSUS_PLAYER2_S": {"value": "PLAYER 2", "locID": "STR_REP_VERSUS_PLAYER2"},
	"STR_REP_VERSUS_LETTER_V": {"value": "V", "locID": ""},
	"STR_REP_VERSUS_LETTER_V_S": {"value": "V", "locID": "STR_REP_VERSUS_LETTER_V"},
	"STR_REP_VERSUS_LETTER_S": {"value": "s", "locID": ""},
	"STR_REP_VERSUS_LETTER_S_S": {"value": "s", "locID": "STR_REP_VERSUS_LETTER_S"},
	"STR_SELECTCHARACTERVS_TITLE": {"value": "SELECT CHARACTER", "locID": ""},
	"STR_SELECTSTAGE_TITLE": {"value": "SELECT STAGE", "locID": ""},
	"STR_SELECTCHALLENTE_TITLE": {"value": "SELECT CHALLENGE", "locID": ""},
	"STR_REP_CHALLENGE_TITLE_N1": {"value": "HALF-DONE", "locID": ""},
	"STR_REP_CHALLENGE_DESCRIPTION_N1": {"value": "Start each round with half health meter", "locID": ""},
	"STR_REP_CHALLENGE_TITLE_N2": {"value": "BASIC MODE", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N2": {"value": "One-hit-KO rounds", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N3": {"value": "GOTTA GET THE BEANS", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N3": {"value": "First to land their special attack wins", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N4": {"value": "IT'S RUSH HOUR", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N4": {"value": "Win the round in less than 20 seconds", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N5": {"value": "C-C-C-COMBO!!", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N5": {"value": "No damage - perform a 5 combo", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N6": {"value": "TOUGHIE", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N6": {"value": "Opponent does double damage", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N7": {"value": "STAMPEDE", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N7": {"value": "Hit the other player with goats", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N8": {"value": "BITE THE DUST", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N8": {"value": "Diving to the floor hurts you", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N9": {"value": "ENDURE!", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N9": {"value": "Survive 30 seconds without being hit", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N10": {"value": "VITAMIN PACKED", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N10": {"value": "Opponent recovers health continuously", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N11": {"value": "WEAK KNEES", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N11": {"value": "Jumping drains a little percentage of your HP", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N12": {"value": "KEEP YOUR DISTANCE", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N12": {"value": "One dive charges your special bar", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N13": {"value": "THE FLOOR IS LAVA", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N13": {"value": "Staying on the floor drains your health", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N14": {"value": "NO BIG DEAL", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N14": {"value": "Beat Giant Bill!", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_CHALLENGE_TITLE_N15": {"value": "THIS ENDS HERE!", "locID": "STR_REP_CHALLENGE_TITLE_N1"},
	"STR_REP_CHALLENGE_DESCRIPTION_N15": {"value": "Finish the round with a special attack", "locID": "STR_REP_CHALLENGE_DESCRIPTION_N1"},
	"STR_REP_HELP_TITLE_1": {"value": "JUMPING", "locID": "STR_REP_HELP_TITLE_1"},
	"STR_REP_HELP_TITLE_2": {"value": "DIVE ATTACK", "locID": "STR_REP_HELP_TITLE_1"},
	"STR_REP_HELP_TITLE_3": {"value": "BACKDASH", "locID": "STR_REP_HELP_TITLE_1"},
	"STR_REP_HELP_TITLE_4": {"value": "TACKLE", "locID": "STR_REP_HELP_TITLE_1"},
	"STR_REP_HELP_TITLE_5": {"value": "RECOVER", "locID": "STR_REP_HELP_TITLE_1"},
	"STR_REP_HELP_TITLE_6": {"value": "SPECIAL ATTACK", "locID": "STR_REP_HELP_TITLE_1"},
	"STR_HELP_TITLE": {"value": "HELP", "locID": ""},
	"STR_HELP_DESCRIPTION_1": {"value": "Swipe up to jump and double jump", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_2": {"value": "Swipe down in the air to dive", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_3": {"value": "Swipe backwards to backdash", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_4": {"value": "Swipe forward to tackle", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_5": {"value": "Tap the screen repeatedly to recover when stunned", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_6": {"value": "Double tap to perform a special attack when the special meter is glowing", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_PC_1": {"value": "Press W/UP to jump and double jump", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_PC_2": {"value": "Press S/DOWN in the air to dive", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_PC_3": {"value": "Press backwards A/LEFT or D/RIGHT to backdash", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_PC_4": {"value": "Press forward A/LEFT or D/RIGHT to tackle", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_PC_5": {"value": "Press buttons repeatedly to recover when stunned", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_HELP_DESCRIPTION_PC_6": {"value": "Press SPACEBAR/ENTER to perform a special attack when the special meter is glowing", "locID": "STR_HELP_DESCRIPTION_1"},
	"STR_SELECTSTAGE_DESCRIPTION": {"value": "Here goes the stage description", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_0": {"value": "GREENS' FRONT YARD", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_1": {"value": "BIG COFFEE", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_2": {"value": "SUBWAY", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_3": {"value": "RACCOON PARK", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_4": {"value": "CITY STREETS", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_5": {"value": "CITY PARK", "locID": ""},
	"STR_SELECTSTAGE_DESCRIPTION_6": {"value": "GREENS' BACK YARD", "locID": ""},
	"STR_MESSAGE_HIT_NUMBER": {"value": "#", "locID": ""},
	"STR_MESSAGE_HIT_NUMBER_S": {"value": "#", "locID": ""},
	"STR_MESSAGE_HIT": {"value": "HIT", "locID": ""},
	"STR_MESSAGE_HIT_S": {"value": "HIT", "locID": ""},
	"STR_REP_MESSAGE_DESTROYED": {"value": "DESTROYED", "locID": ""},
	"STR_REP_MESSAGE_DESTROYED_S": {"value": "DESTROYED", "locID": "STR_REP_MESSAGE_DESTROYED"},
	"STR_REP_MESSAGE_TRAINING": {"value": "TRAINING", "locID": "STR_REP_MESSAGE_ROUND"},
	"STR_REP_MESSAGE_TRAINING_S": {"value": "TRAINING", "locID": "STR_REP_MESSAGE_ROUND"},
	"STR_REP_MESSAGE_ROUND": {"value": "ROUND #", "locID": ""},
	"STR_REP_MESSAGE_ROUND_S": {"value": "ROUND #", "locID": ""},
	"STR_REP_MESSAGE_FIGHT": {"value": "FIGHT!", "locID": "STR_REP_MESSAGE_ROUND"},
	"STR_REP_MESSAGE_FIGHT_S": {"value": "FIGHT!", "locID": "STR_REP_MESSAGE_FIGHT"},
	"STR_MESSAGE_FIGHT02": {"value": "FIGHT!", "locID": ""},
	"STR_MESSAGE_FIGHT02_S": {"value": "FIGHT!", "locID": ""},
	"STR_MESSAGE_FIGHT03": {"value": "FIGHT!", "locID": ""},
	"STR_MESSAGE_FIGHT03_S": {"value": "FIGHT!", "locID": ""},
	"STR_MESSAGE_FINALROUND": {"value": "FINAL ROUND", "locID": ""},
	"STR_MESSAGE_FINALROUND_S": {"value": "FINAL ROUND", "locID": ""},
	"STR_MESSAGE_TIE_BRAKER_S": {"value": "TIEBREAKER!", "locID": ""},
	"STR_MESSAGE_TIE_BRAKER": {"value": "TIEBREAKER!", "locID": ""},
	"STR_MESSAGE_TIME_UP": {"value": "TIME’S UP!", "locID": ""},
	"STR_MESSAGE_TIME_UP_S": {"value": "TIME’S UP!", "locID": ""},
	"STR_REP_MESSAGE_PERFECT": {"value": "PERFECT!", "locID": ""},
	"STR_REP_MESSAGE_PERFECT_S": {"value": "PERFECT!", "locID": "STR_REP_MESSAGE_PERFECT"},
	"STR_MESSAGE_FAILED": {"value": "CHALLENGE FAILED", "locID": ""},
	"STR_MESSAGE_FAILED_S": {"value": "CHALLENGE FAILED", "locID": ""},
	"STR_REP_MESSAGE_COMPLETE": {"value": "CHALLENGE COMPLETE", "locID": ""},
	"STR_REP_MESSAGE_COMPLETE_S": {"value": "CHALLENGE COMPLETE", "locID": "STR_REP_MESSAGE_COMPLETE"},
	"STR_TROPHIES_TITLE": {"value": "TROPHIES", "locID": ""},
	"STR_TROPHIES_NAME": {"value": "Trophy name", "locID": ""},
	"STR_TROPHIES_DESCRIPTION": {"value": "Here goes the trophy description", "locID": ""},
	"STR_REP_ENDLEVEL_VSMODE_PLAYER_ID": {"value": "PLAYER #", "locID": ""},
	"STR_REP_ENDLEVEL_VSMODE_LOSE": {"value": "DEFEAT", "locID": ""},
	"STR_REP_ENDLEVEL_VSMODE_LOSE_S": {"value": "DEFEAT", "locID": "STR_REP_ENDLEVEL_VSMODE_LOSE"},
	"STR_REP_ENDLEVEL_VSMODE_WIN": {"value": "VICTORY", "locID": ""},
	"STR_REP_ENDLEVEL_VSMODE_WIN_S": {"value": "VICTORY", "locID": "STR_REP_ENDLEVEL_VSMODE_WIN"},
	"STR_REP_ENDLEVEL_WIN0": {"value": "VICTORY", "locID": "STR_REP_ENDLEVEL_VSMODE_WIN"},
	"STR_REP_ENDLEVEL_WIN1": {"value": "GOT 'EM", "locID": "STR_REP_ENDLEVEL_VSMODE_WIN"},
	"STR_REP_ENDLEVEL_LOSE0": {"value": "DEFEAT", "locID": "STR_REP_ENDLEVEL_VSMODE_LOSE"},
	"STR_REP_ENDLEVEL_LOSE1": {"value": "WHOOPS", "locID": "STR_REP_ENDLEVEL_VSMODE_LOSE"},
	"STR_REP_ENDLEVEL_LOSE2": {"value": "UH-OH", "locID": "STR_REP_ENDLEVEL_VSMODE_LOSE"},
	"STR_REP_ENDLEVEL_LOSE3": {"value": "NOPE!", "locID": "STR_REP_ENDLEVEL_VSMODE_LOSE"},
	"STR_ENDLEVEL_VSMODE_LOSE_S": {"value": "DEFEAT", "locID": ""},
	"STR_ENDLEVEL_VSMODE_CHARA1": {"value": "CHARACTER NAME", "locID": ""},
	"STR_ENDGAME_TEXT": {"value": "CONGRATS! YOU’RE AN OFFICIAL GREEN", "locID": ""},
	"STR_SELECTDIFFICULTY_TITLE": {"value": "HOW BAD YA WANNA WRASSLE?", "locID": ""},
	"STR_SELECTDIFFICULTY_D1": {"value": "FOOLIN' (EASY)", "locID": ""},
	"STR_SELECTDIFFICULTY_D2": {"value": "TOOLIN' (MEDIUM)", "locID": ""},
	"STR_SELECTDIFFICULTY_D3": {"value": "GRUELIN' (HARD)", "locID": ""},
	"STR_SELECTDIFFICULTY_LOCKED": {"value": "LOCKED", "locID": ""},
	"STR_REP_DIALOGUE_CRICKET_01_01": {"value": "Hmm… Not many vicious animals to fight in the city. Good thing I live on a farm! You're mine, demon!", "locID": ""},
	"STR_REP_DIALOGUE_CRICKET_01_02": {"value": "B'caw?", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_02_01": {"value": "Okay, pig! Cricket Green—or just Cricket until I earn my last name—is coming for ya!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_02_02": {"value": "Oink oink!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_03_01": {"value": "If an animal won't cut it for Gramma, maybe a human will! (Remember Remy, you gotta let me win)!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_03_02": {"value": "Oh boy, my first fight! Please don’t tell my parents.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_04_01": {"value": "Bring it on, sister! I'm gonna become a Green today one way or another!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_04_02": {"value": "What a beautiful day for a battle.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_05_01": {"value": "Bring it on!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_05_02": {"value": "Don’t make me hurt ya now!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_06_01": {"value": "This is gonna be fun!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_06_02": {"value": "I may be old but I’ll outlive you!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_STAT_01": {"value": "A lion! That's the a perfect vicious animal to defeat!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_STAT_02": {"value": "(Cold statue silence)", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_CRICKET_STAT_03": {"value": "Frightened in terror, huh? You should be!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_01_01": {"value": "Hi there. Care to tango?", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_01_02": {"value": "Bcawk!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_02_01": {"value": "Time to unleash the beast. (By the way, I am the beast).", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_02_02": {"value": "Oiiiiiink...", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_03_01": {"value": "Thanks for helping me earn my family name, Remy. Get ready to crumble!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_03_02": {"value": "Wait, are we fighting for real? I thought we were just foolin'!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_04_01": {"value": "I always knew the day would come where I would have to best you in battle, brother.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_04_02": {"value": "You ain’t got a chance!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_05_01": {"value": "You’re about to see cute li’l birds flyin’ round your head.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_05_02": {"value": "If you beat me, you’re grounded.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_05_03": {"value": "If I beat you, you'll be grounded. Cause you'll be on the ground.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_06_01": {"value": "Watch out. I just turned off my conscience.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_06_02": {"value": "My teeth may be fake but they’ll bite ya for real!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_STAT_01": {"value": "You look like a worthy opponent.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_STAT_02": {"value": "(Cold statue silence)", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_TILLY_STAT_03": {"value": "No need for such strong language.", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_BOSS_00": {"value": "Nice work… But I was holdin' back! Prepare to face my ULTIMATE GRAMMA WRATH!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_BOSS_01": {"value": "I ain't beat yet, girlie! No more holdin' back… Time for GRAMMA UNLEASHED!", "locID": "STR_REP_DIALOGUE_CRICKET_01_01"},
	"STR_REP_DIALOGUE_NAME_CRICKET": {"value": "Cricket", "locID": ""},
	"STR_REP_DIALOGUE_NAME_TILLY": {"value": "Tilly", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_DIALOGUE_NAME_GRAMMA": {"value": "Gramma", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_DIALOGUE_NAME_REMY": {"value": "Remy", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_DIALOGUE_NAME_BILL": {"value": "Bill", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_DIALOGUE_NAME_PIG": {"value": "Pig", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_DIALOGUE_NAME_CHICKEN": {"value": "Chicken", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S1_1": {"value": "Now, let's go through the basics.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S1_2": {"value": "Press W to jump.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S1_3": {"value": "Ok, now attack by pressing S.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S1_4": {"value": "Good, I guess. But not good enough!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S2_1": {"value": "That puny jump ain't gonna cut it! Try a double jump…", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S2_2": {"value": "Jump and press W in mid-air to double jump.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S2_3": {"value": "Now double jump and hit them where it hurts", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S2_4": {"value": "Decent. When you dive, you fill your special meter, remember this.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S3_1": {"value": "Let's try moving on the ground, use backdash by pressing the back button (A).", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S3_2": {"value": "Ok, try evading this attack.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S3_3": {"value": "Not great, but it'll do. You can tackle by pressing the forward button (D).", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S4_1": {"value": "You can throw a special attack by pressing spacebar.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S4_2": {"value": "If your meter is full, you can do more than just a tickle", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S4_3": {"value": "Like this one.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S4_4": {"value": "When stunned, you can get up by quickly pressing any button a whole buncha times!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_PC_S4_5": {"value": "Your training is complete, now go find a worthy opponent and become a true Green!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S1_1": {"value": "Now, let's go through the basics.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S1_2": {"value": "Swipe up to jump.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S1_3": {"value": "Ok, now attack by swiping down.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S1_4": {"value": "Good, I guess. But not good enough!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S2_1": {"value": "That puny jump ain't gonna cut it! Try a double jump…", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S2_2": {"value": "Jump and swipe in mid-air to double jump.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S2_3": {"value": "Now perform a double jump and hit them where it hurts with a diving attack.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S2_4": {"value": "Decent. Whenever you dive, you will fill your special meter, remember this.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S3_1": {"value": "Let's try moving on the ground, you can backdash by swiping backwards.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S3_2": {"value": "Ok, try evading this attack.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S3_3": {"value": "Not great, but it'll do. You can tackle by swiping forward.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S4_1": {"value": "You can throw a special attack with half of your special meter by double tapping.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S4_2": {"value": "If you fill your special meter, you can throw something that will do more than just a tickle", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S4_3": {"value": "Like this one.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S4_4": {"value": "When stunned, you can get up by quickly tappin' the screen a whole buncha times!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_S4_5": {"value": "Your training is complete, now go find a worthy opponent and become a true Green!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_MISS": {"value": "No, that's not it, try again whippersnapper.", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_TUTORIAL_BTN_JUMP_P1": {"value": "W", "locID": ""},
	"STR_REP_TUTORIAL_BTN_JUMP_P2": {"value": "ARROW_UP", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_DIVE_P1": {"value": "S", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_DIVE_P2": {"value": "ARROW_DOWN", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_BACK_P1": {"value": "A", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_BACK_P2": {"value": "ARROW_RIGHT", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_FWD_P1": {"value": "D", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_FWD_P2": {"value": "ARROW_LEFT", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_SPEC_P1": {"value": "SPACE", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BTN_SPEC_P2": {"value": "ENTER", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_LETTER_01": {"value": "W", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_LETTER_02": {"value": "A", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BUTTON01": {"value": "SPACE", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_TUTORIAL_BUTTON02": {"value": "ENTER", "locID": "STR_REP_TUTORIAL_BTN_JUMP_P1"},
	"STR_REP_WIN_QUOTE_CRICKET01": {"value": "Bingo Bango!", "locID": "STR_REP_DIALOGUE_NAME_CRICKET"},
	"STR_REP_WIN_QUOTE_CRICKET02": {"value": "I’m a fearless boy!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_CRICKET03": {"value": "Dang!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_CRICKET04": {"value": "Ayiyiyiyi!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_CRICKET05": {"value": "I ain’t afraid to get dirty!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_CRICKET06": {"value": "Cricket Green, nice to beat ya!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_TILLY01": {"value": "Get Ready!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_TILLY02": {"value": "I have seen danger… and I love it.", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_TILLY03": {"value": "I hope we can still be friends after this.", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_TILLY04": {"value": "Tilly Tornado! ", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_TILLY05": {"value": "Ouchie wa-wa!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_TILLY06": {"value": "The spirit of a goat is within me.", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_GRAMMA": {"value": "Don’t mess with Gramma!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_REMY": {"value": "Finally my karate classes paid off!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_BILL": {"value": "Take it easy now.", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_PIG": {"value": "Oiiink oink!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_WIN_QUOTE_CHICKEN": {"value": "Cockadoodledoo!", "locID": "STR_REP_WIN_QUOTE_CRICKET01"},
	"STR_REP_NEW_TROPHY_TITLE01": {"value": "KAPOW!", "locID": ""},
	"STR_REP_NEW_TROPHY_TITLE02": {"value": "What are ya, Chicken?", "locID": "STR_REP_NEW_TROPHY_TITLE01"},
	"STR_REP_NEW_TROPHY_TITLE03": {"value": "True Green", "locID": "STR_REP_NEW_TROPHY_TITLE01"},
	"STR_REP_NEW_TROPHY_TITLE04": {"value": "Untouchable", "locID": "STR_REP_NEW_TROPHY_TITLE01"},
	"STR_REP_NEW_TROPHY_TITLE05": {"value": "Truest Green", "locID": "STR_REP_NEW_TROPHY_TITLE01"},
	"STR_REP_NEW_TROPHY_DESCRIPTION01": {"value": "Land a fully charged special attack", "locID": ""},
	"STR_REP_NEW_TROPHY_DESCRIPTION02": {"value": "Defeat Chicken", "locID": "STR_REP_NEW_TROPHY_DESCRIPTION01"},
	"STR_REP_NEW_TROPHY_DESCRIPTION03": {"value": "Defeat Gramma Alice", "locID": "STR_REP_NEW_TROPHY_DESCRIPTION01"},
	"STR_REP_NEW_CHARACTER_TITLE": {"value": "New Character", "locID": ""},
	"STR_REP_NEW_CHARACTER_DESCRIPTION": {"value": "Now you can play with #", "locID": ""},
	"STR_REP_NEW_SKIN_TITLE": {"value": "New Costume", "locID": ""},
	"STR_REP_NEW_SKIN_DESCRIPTION": {"value": "You have a new costume for #", "locID": ""},
	"STR_REP_NEW_MODE_TITLE": {"value": "New Mode", "locID": ""},
	"STR_REP_NEW_MODE_DESCRIPTION": {"value": "Now you can play in the Challenge Mode", "locID": ""},
	"STR_REP_HARD_MODE_TITLE": {"value": "New Difficulty", "locID": ""},
	"STR_REP_HARD_MODE_DESCRIPTION": {"value": "Now you can play in Hard Mode", "locID": ""},
	"STR_REP_MODE_LOCKED_TITLE": {"value": "Locked", "locID": ""},
	"STR_REP_MODE_LOCKED_DESCRIPTION": {"value": "Finish Story Mode to unlock the Challenge Mode", "locID": ""},
	"STR_REP_MESSAGE_FIRSTHIT": {"value": "FIRST HIT", "locID": ""},
	"STR_REP_MESSAGE_FIRSTHIT_S": {"value": "FIRST HIT", "locID": "STR_REP_MESSAGE_FIRSTHIT"},
	"STR_REP_MESSAGE_K": {"value": "K", "locID": ""},
	"STR_REP_MESSAGE_K_S": {"value": "K", "locID": "STR_REP_MESSAGE_K"},
	"STR_REP_MESSAGE_O": {"value": "O", "locID": ""},
	"STR_REP_MESSAGE_O_S": {"value": "O", "locID": "STR_REP_MESSAGE_O"},
	"STR_REP_MESSAGE_CHARACTERNAME_0": {"value": "CRICKET", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_0_S": {"value": "CRICKET", "locID": "STR_REP_MESSAGE_CHARACTERNAME_1"},
	"STR_REP_MESSAGE_CHARACTERNAME_1": {"value": "TILLY", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_1_S": {"value": "TILLY", "locID": "STR_REP_MESSAGE_CHARACTERNAME_2"},
	"STR_REP_MESSAGE_CHARACTERNAME_6": {"value": "GRAMMA", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_6_S": {"value": "GRAMMA", "locID": "STR_REP_MESSAGE_CHARACTERNAME_3"},
	"STR_REP_MESSAGE_CHARACTERNAME_4": {"value": "REMY", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_4_S": {"value": "REMY", "locID": "STR_REP_MESSAGE_CHARACTERNAME_4"},
	"STR_REP_MESSAGE_CHARACTERNAME_5": {"value": "BILL", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_5_S": {"value": "BILL", "locID": "STR_REP_MESSAGE_CHARACTERNAME_5"},
	"STR_REP_MESSAGE_CHARACTERNAME_2": {"value": "PIG", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_2_S": {"value": "PIG", "locID": "STR_REP_MESSAGE_CHARACTERNAME_6"},
	"STR_REP_MESSAGE_CHARACTERNAME_3": {"value": "CHICKEN", "locID": ""},
	"STR_REP_MESSAGE_CHARACTERNAME_3_S": {"value": "CHICKEN", "locID": "STR_REP_MESSAGE_CHARACTERNAME_7"},
	"STR_REP_CHARACTERNAME_GIANT": {"value": "GIANT", "locID": ""},
	"STR_REP_MESSAGE_WINS": {"value": "WINS", "locID": ""},
	"STR_REP_MESSAGE_WINS_S": {"value": "WINS", "locID": "STR_REP_MESSAGE_WINS"},
	"STR_REP_NEW_TROPHY_DESCRIPTION04": {"value": "Beat an enemy without receiving damage", "locID": "STR_REP_NEW_TROPHY_DESCRIPTION01"},
	"STR_REP_NEW_TROPHY_DESCRIPTION05": {"value": "Complete all challenges", "locID": "STR_REP_NEW_TROPHY_DESCRIPTION01"},
	"STR_ENDLEVEL_VSMODE_CHARA2": {"value": "CHARACTER NAME", "locID": ""},
	"STR_REP_TUTORIAL_SKIP": {"value": "Press any button to start", "locID": ""},
	"STR_REP_TUTORIAL_SKIP_S": {"value": "Press any button to start", "locID": "STR_REP_TUTORIAL_SKIP"},
	"STR_REP_TUTORIAL_SKIP_M": {"value": "Tap anywhere to start", "locID": "STR_REP_TUTORIAL_SKIP"},
	"STR_POST_FIGHT_STAT_DIAG_CRICKET_01": {"value": "That was a STATUE. Doesn't count AT ALL!", "locID": ""},
	"STR_POST_FIGHT_STAT2_DIAG_CRICKET_01": {"value": "You couldn't even defeat a statue?! Keep looking or you will never become a Green!", "locID": ""},
	"STR_POST_FIGHT_STAT_DIAG_TILLY_02": {"value": "You're right. I didn't want it to get to this. But I have no other option… weee!", "locID": ""},
	"STR_POST_FIGHT_STAT_DIAG_CRICKET_02": {"value": "Ok, ok… you're right. I think I'll have to up the ante—!", "locID": ""},
	"STR_POST_FIGHT_1_DIAG_CRICKET_01": {"value": "That doesn’t count! Keep looking or else you won’t ever be a true Green!", "locID": ""},
	"STR_POST_FIGHT_2_DIAG_CRICKET_01": {"value": "That’s not good enough! You’re not even trying!", "locID": ""},
	"STR_POST_FIGHT_2_DIAG_CRICKET_02": {"value": "Not good enough, huh? I'll have to try somewhere else…", "locID": ""},
	"STR_POST_FIGHT_3_DIAG_CRICKET_01": {"value": "Nope. Doesn’t count!", "locID": ""},
	"STR_POST_FIGHT_3_DIAG_CRICKET_02": {"value": "Whaaat?!", "locID": ""},
	"STR_POST_FIGHT_4_DIAG_CRICKET_01": {"value": "Are you kidding me? That’s not a vicious animal!", "locID": ""},
	"STR_POST_FIGHT_4_DIAG_CRICKET_02": {"value": "A vicious animal... I think I know where I can find one...", "locID": ""},
	"STR_POST_FIGHT_5_DIAG_CRICKET_01": {"value": "Congratulations on finding a worthy opponent! Now, prepare for a whuppin’!", "locID": ""},
	"STR_POST_FIGHT_2_DIAG_TILLY_02": {"value": "Well… I guess I'll have to go search somewhere else…", "locID": ""},
	"STR_POST_FIGHT_3_DIAG_TILLY_02": {"value": "Oh…", "locID": ""},
	"STR_POST_FIGHT_4_DIAG_TILLY_02": {"value": "Hmm... I know where I can find such a beastly creature...", "locID": ""}
};
