window['swt_ui'] = window['swt_ui'].concat([
	{
		"string": "STR_TROPHIES_DESCRIPTION",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "580",
		"height": "80",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTrophydescription",
		"type": "text"
	},
	{
		"string": "STR_TROPHIES_NAME",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "50",
		"size_ltr": "36",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTrophyname",
		"type": "text"
	},
	{
		"string": "STR_TROPHIES_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "550",
		"height": "100",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_D3",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtHardOver",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_D3",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtHard",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_LOCKED",
		"color": "#242424",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtLocked",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_D2",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtNormalOver",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_D2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtNormal",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_D1",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtEasyOver",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_D1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtEasy",
		"type": "text"
	},
	{
		"string": "STR_SELECTDIFFICULTY_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "550",
		"height": "100",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenDifficulty",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_SELECTCHALLENTE_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "550",
		"height": "100",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenChallenge",
		"control": "mcGuiTxtChallenge",
		"type": "text"
	},
	{
		"string": "STR_ANIMATION_TITLE_CRICKET",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "450",
		"height": "65",
		"size_ltr": "64",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "64",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMainAnimations",
		"control": "mcGuiTxtChallenge",
		"type": "text"
	},
	{
		"string": "STR_VSMODE_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "320",
		"height": "94",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupVSmode",
		"control": "mcGuiTxtTitle2",
		"type": "text"
	},
	{
		"string": "STR_VSMODE_PLAYER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "360",
		"height": "80",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupVSmode",
		"control": "mcGuiTxtTitle1",
		"type": "text"
	},
	{
		"string": "STR_VSMODE_CPU",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "360",
		"height": "80",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupVSmode",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_TRAINING_DESCRIPTION",
		"color": "#119851",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "30",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupTutorial",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_TRAINING_TITLE",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "56",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "56",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupTutorial",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_MAINMENU_CHALLENGE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "348",
		"height": "80",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectMode",
		"control": "mcGuiTxtChallenge",
		"type": "text"
	},
	{
		"string": "STR_MAINMENU_TUTORIAL",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "348",
		"height": "80",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectMode",
		"control": "mcGuiTxtTutorial",
		"type": "text"
	},
	{
		"string": "STR_MAINMENU_STORY",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "328",
		"height": "80",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectMode",
		"control": "mcGuiTxtStory",
		"type": "text"
	},
	{
		"string": "STR_MAINMENU_VERSUS",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "348",
		"height": "80",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectMode",
		"control": "mcGuiTxtVersus",
		"type": "text"
	},
	{
		"string": "STR_MAINMENU_SELECTMODE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "320",
		"height": "94",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectMode",
		"control": "mcGuiTxtGamename",
		"type": "text"
	},
	{
		"string": "STR_RESET_DESCRIPTION",
		"color": "#119851",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "30",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupReset",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_RESET_TITLE",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "56",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "56",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupReset",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_PAUSE_TITLE",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "450",
		"height": "100",
		"size_ltr": "56",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "56",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupPause",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_CONTINUE_DESCRIPTION",
		"color": "#119851",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "30",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupContinue",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_CONTINUE_TITLE",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "56",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "56",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupContinue",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_CONFIRM_DESCRIPTION",
		"color": "#119851",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "30",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupConfirm",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_CONFIRM_TITLE",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "80",
		"size_ltr": "56",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "56",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupConfirm",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_DESCRIPTION_N1",
		"color": "#000000",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "485",
		"height": "60",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtDescriptionOffOver",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_DESCRIPTION_N1",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "485",
		"height": "60",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtDescriptionOff",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_DESCRIPTION_N1",
		"color": "#00955b",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "485",
		"height": "60",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtDescriptionOnOver",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_DESCRIPTION_N1",
		"color": "#4fff9e",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "485",
		"height": "60",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtDescriptionOn",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_TITLE_N1",
		"color": "#000000",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "470",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtTitleOffOver",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_TITLE_N1",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "470",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtTitleOff",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_TITLE_N1",
		"color": "#00955b",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "470",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtTitleOnOver",
		"type": "text"
	},
	{
		"string": "STR_REP_CHALLENGE_TITLE_N1",
		"color": "#4fff9e",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "470",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemChallenge",
		"control": "mcGuiTxtTitleOn",
		"type": "text"
	},
	{
		"string": "STR_MAINMENU_CHALLENGE",
		"color": "#454545",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "348",
		"height": "80",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiItemButton",
		"control": "mcGuiTxtChallenge",
		"type": "text"
	},
	{
		"string": "STR_CUTSCENE_DIALOG_CRICKET_01_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "750",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenCutscene",
		"control": "mcGuiTxtCutscene",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_1S",
		"color": "#a41401",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "100",
		"size_ltr": "110",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "110",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayerNameS01",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "100",
		"size_ltr": "110",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "110",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayerName01",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_PLAYER1_S",
		"color": "#a41401",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayer01S",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_PLAYER1",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayer01",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_2S",
		"color": "#04559e",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "100",
		"size_ltr": "110",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "110",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayerNameS02",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "100",
		"size_ltr": "110",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "110",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayerName02",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_PLAYER2_S",
		"color": "#04559e",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayer02S",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_PLAYER2",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "30",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextPlayer02",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_LETTER_V",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "50",
		"size_ltr": "242",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "242",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextVersusS01",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_LETTER_V_S",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "50",
		"size_ltr": "242",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "242",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextVersus01",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_LETTER_S_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "50",
		"size_ltr": "242",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "242",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextVersusS02",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_LETTER_S",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "50",
		"size_ltr": "242",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "242",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenVersus",
		"control": "mcGuiTextVersus02",
		"type": "text"
	},
	{
		"string": "STR_SELECTSTAGE_DESCRIPTION",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "580",
		"height": "100",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectStage",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_SELECTSTAGE_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "550",
		"height": "100",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenSelectStage",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_VS_CHARACTERNAME_2S",
		"color": "#0e1d43",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "280",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacterVS",
		"control": "mcGuiTxtCharacter2_S",
		"type": "text"
	},
	{
		"string": "STR_REP_VS_CHARACTERNAME_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "280",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacterVS",
		"control": "mcGuiTxtCharacter2",
		"type": "text"
	},
	{
		"string": "STR_REP_VS_CHARACTERNAME_1S",
		"color": "#680b0b",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "280",
		"height": "50",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacterVS",
		"control": "mcGuiTxtCharacter1_S",
		"type": "text"
	},
	{
		"string": "STR_REP_VS_CHARACTERNAME_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "280",
		"height": "50",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacterVS",
		"control": "mcGuiTxtCharacter1",
		"type": "text"
	},
	{
		"string": "STR_SELECTCHARACTERVS_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "550",
		"height": "100",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenSelectCharacterVS",
		"control": "mcGuiTxtTitleVS",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_2S",
		"color": "#0e1d43",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacter",
		"control": "mcGuiTxtCharacter2_S",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacter",
		"control": "mcGuiTxtCharacter2",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_1S",
		"color": "#0e1d43",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacter",
		"control": "mcGuiTxtCharacter1_S",
		"type": "text"
	},
	{
		"string": "STR_REP_STORY_CHARACTERNAME_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenSelectCharacter",
		"control": "mcGuiTxtCharacter1",
		"type": "text"
	},
	{
		"string": "STR_SELECTCHARACTER_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "550",
		"height": "100",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenSelectCharacter",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_ENDGAME_TEXT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "400",
		"height": "100",
		"size_ltr": "60",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "60",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndGame",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_ANIMATION_TITLE_TILLY",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "60",
		"size_ltr": "60",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "60",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectAnimations",
		"control": "mcGuiText02",
		"type": "text"
	},
	{
		"string": "STR_ANIMATION_TITLE_CRICKET",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "60",
		"size_ltr": "60",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "60",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupSelectAnimations",
		"control": "mcGuiText01",
		"type": "text"
	},
	{
		"string": "STR_REP_MODE_LOCKED_TITLE",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "400",
		"height": "35",
		"size_ltr": "36",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupLockedMode",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_MODE_LOCKED_DESCRIPTION",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "400",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupLockedMode",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_REP_SELECT_CHARACTER_READY_2S",
		"color": "#003592",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupBlackBox02",
		"control": "mcGuiTxtReadyS",
		"type": "text"
	},
	{
		"string": "STR_REP_SELECT_CHARACTER_READY_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupBlackBox02",
		"control": "mcGuiTxtReady",
		"type": "text"
	},
	{
		"string": "STR_REP_SELECT_CHARACTER_READY_1S",
		"color": "#920200",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupBlackBox01",
		"control": "mcGuiTxtReadyS",
		"type": "text"
	},
	{
		"string": "STR_REP_SELECT_CHARACTER_READY_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiPopupBlackBox01",
		"control": "mcGuiTxtReady",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_PLAYER1",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "70",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "70",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialMovilButtonComplete",
		"control": "mcGuiTextPlayer1",
		"type": "text"
	},
	{
		"string": "STR_REP_VERSUS_PLAYER2",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "70",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "70",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialMovilButtonComplete",
		"control": "mcGuiTextPlayer2",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_SKIP_S",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialMovilButtonComplete",
		"control": "mcGuiSkipTextS",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_SKIP",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialMovilButtonComplete",
		"control": "mcGuiSkipText",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonDoubleJump",
		"control": "mcGuiTxtW",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonDoubleJump",
		"control": "mcGuiTxtA",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt01",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt02",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt03",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt04",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_BUTTON01",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt05",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_SKIP_S",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiSkipTextS",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_SKIP",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiSkipText",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt06",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt07",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt08",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt09",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_BUTTON02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButtonComplete",
		"control": "mcGuiTxt10",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_LETTER_02",
		"color": "#089d54",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiTutorialButton",
		"control": "mcGuiTxtA",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN_S",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenRematch",
		"control": "mcGuiTxtWinS03",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN_S",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenRematch",
		"control": "mcGuiTxtWinS02",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN_S",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenRematch",
		"control": "mcGuiTxtWinS",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenRematch",
		"control": "mcGuiTxtWin",
		"type": "text"
	},
	{
		"string": "STR_REP_WIN_QUOTE_CRICKET02",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "700",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "32",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenRematch",
		"control": "mcGuiTxtVictoryQuote",
		"type": "text"
	},
	{
		"string": "STR_HELP_TITLE",
		"color": "#26b867",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "350",
		"height": "35",
		"size_ltr": "64",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "64",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenHelp",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN_S",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtWinS03",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN_S",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtWinS02",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN_S",
		"color": "#09603b",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtWinS",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_WIN",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtWin",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_LOSE_S",
		"color": "#930b0a",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtLoseS03",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_LOSE_S",
		"color": "#930b0a",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtLoseS02",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_LOSE_S",
		"color": "#930b0a",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtLoseS",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_VSMODE_LOSE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "120",
		"size_ltr": "120",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtLose",
		"type": "text"
	},
	{
		"string": "STR_REP_WIN_QUOTE_CRICKET02",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "700",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "32",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenEndlevel",
		"control": "mcGuiTxtVictoryQuote",
		"type": "text"
	},
	{
		"string": "STR_REP_NEW_TROPHY_TITLE02",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "450",
		"height": "35",
		"size_ltr": "36",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupNewTrophy",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_NEW_TROPHY_DESCRIPTION02",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "500",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupNewTrophy",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_REP_NEW_SKIN_TITLE",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "450",
		"height": "35",
		"size_ltr": "36",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupNewSkin",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_NEW_SKIN_DESCRIPTION",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "500",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupNewSkin",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_REP_NEW_CHARACTER_TITLE",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "400",
		"height": "35",
		"size_ltr": "36",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupNewCharacter",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_NEW_CHARACTER_DESCRIPTION",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "400",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupNewCharacter",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_NAME_CRICKET",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "36",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupDialogue",
		"control": "mcGuiTxtName01",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_NAME_TILLY",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "36",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "36",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupDialogue",
		"control": "mcGuiTxtName02",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_CRICKET_01_02",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "350",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupDialogue",
		"control": "mcGuiTxtInfo01",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_CRICKET_01_01",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "1",
		"width": "440",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiPopupDialogue",
		"control": "mcGuiTxtInfo02",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_TIME_UP_S",
		"color": "#470000",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "62",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "62",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTimeOut",
		"control": "mcGuiTextMessage_S",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_TIME_UP",
		"color": "#f82b23",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "62",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "62",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTimeOut",
		"control": "mcGuiTextMessage1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_TIE_BRAKER_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTextMessageTB_S",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_TIE_BRAKER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTextMessageTB",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_TIE_BRAKER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTextMessageTB1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_TIE_BRAKER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTextMessageTB2",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTxtFight_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTxtFight",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageTieBreaker",
		"control": "mcGuiTxtFight1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_ROUND_S",
		"color": "#7f2400",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtRound_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_ROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtRound",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_ROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtRound1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_ROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtRound2",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_ROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtRound3",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_ROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtRound4",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtFight_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtFight",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageRound",
		"control": "mcGuiTxtFight1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_CHARACTERNAME_1_S",
		"color": "#7f2400",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "200",
		"size_ltr": "74",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "74",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePlayerWins",
		"control": "mcGuiTxtCharacterNameS",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_CHARACTERNAME_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "200",
		"size_ltr": "74",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "74",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePlayerWins",
		"control": "mcGuiTxtCharacterName",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_WINS_S",
		"color": "#7f2400",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "200",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePlayerWins",
		"control": "mcGuiTxtWinS",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_WINS",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "300",
		"height": "200",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePlayerWins",
		"control": "mcGuiTxtWin",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_PERFECT_S",
		"color": "#02315d",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "100",
		"size_ltr": "86",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "86",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePerfect",
		"control": "mcGuiTxtPerfect_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_PERFECT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "100",
		"size_ltr": "86",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "86",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePerfect",
		"control": "mcGuiTxtPerfect",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_PERFECT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "500",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessagePerfect",
		"control": "mcGuiTxtPerfect1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_K_S",
		"color": "#951403",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "282",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "282",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageKO",
		"control": "mcGuiTextK_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_K",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "282",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "282",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageKO",
		"control": "mcGuiTextK",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_O",
		"color": "#951403",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "254",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "254",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageKO",
		"control": "mcGuiTextO_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_O_S",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "254",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "254",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageKO",
		"control": "mcGuiTextO",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_K",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "282",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "282",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageKO",
		"control": "mcGuiTextK1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_O_S",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "254",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "254",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageKO",
		"control": "mcGuiTextO1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_S",
		"color": "#022719",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit02",
		"control": "mcGuiTextMessage_S2",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit02",
		"control": "mcGuiTextMessage1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_NUMBER_S",
		"color": "#022719",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "98",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "98",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit02",
		"control": "mcGuiTextMessage_S1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_NUMBER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "98",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "98",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit02",
		"control": "mcGuiTextMessage11",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_NUMBER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "98",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "98",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit02",
		"control": "mcGuiTextMessage111",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_S",
		"color": "#022719",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit01",
		"control": "mcGuiTextMessage_S2",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit01",
		"control": "mcGuiTextMessage1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_NUMBER_S",
		"color": "#022719",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "98",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "98",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit01",
		"control": "mcGuiTextMessage_S1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_NUMBER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "98",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "98",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit01",
		"control": "mcGuiTextMessage11",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_HIT_NUMBER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "98",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "98",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageHit01",
		"control": "mcGuiTextMessage111",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIRSTHIT_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFirtsHit02",
		"control": "mcGuiTxtFight_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIRSTHIT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFirtsHit02",
		"control": "mcGuiTxtFight",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIRSTHIT",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFirtsHit01",
		"control": "mcGuiTxtFight_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIRSTHIT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFirtsHit01",
		"control": "mcGuiTxtFight",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FINALROUND_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTextMessageFR_S",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FINALROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTextMessageFR",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FINALROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTextMessageFR1",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FINALROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTextMessageFR2",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FINALROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTextMessageFR3",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FINALROUND",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTextMessageFR4",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTxtFight_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTxtFight",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_FIGHT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "120",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "120",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageFinalRound",
		"control": "mcGuiTxtFight1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_DESTROYED_S",
		"color": "#013c96",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "115",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "115",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageDestroyed",
		"control": "mcGuiTxtDestroyed_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_DESTROYED",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "115",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "115",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiMessageDestroyed",
		"control": "mcGuiTxtDestroyed",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FAILED_S",
		"color": "#470000",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "150",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiChallengeFailed",
		"control": "mcGuiTxtFailed_S",
		"type": "text"
	},
	{
		"string": "STR_MESSAGE_FAILED",
		"color": "#f82b23",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "350",
		"height": "150",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiChallengeFailed",
		"control": "mcGuiTxtFailed",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_COMPLETE_S",
		"color": "#951403",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "750",
		"height": "80",
		"size_ltr": "80",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "80",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiChallengeComplete",
		"control": "mcGuiTxtComplete_S",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_COMPLETE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "750",
		"height": "80",
		"size_ltr": "80",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "80",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiChallengeComplete",
		"control": "mcGuiTxtComplete",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TIMER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "150",
		"height": "70",
		"size_ltr": "63",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "63",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiHUD",
		"control": "mcGuiTimer",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TIMER",
		"color": "#ee0000",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "150",
		"height": "70",
		"size_ltr": "63",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "63",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiHUD",
		"control": "mcGuiTimerWarning",
		"type": "text"
	},
	{
		"string": "STR_HELP_DESCRIPTION_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"width": "320",
		"height": "149",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemHelp",
		"control": "mcGuiTextDescription",
		"type": "text"
	},
	{
		"string": "STR_REP_HELP_TITLE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "300",
		"height": "50",
		"size_ltr": "34",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "34",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiItemHelp",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_LOADING_PERCENT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "132",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "132",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiTxtLoading",
		"type": "text"
	},
	{
		"string": "STR_LOADING_PRELOAD_FONT_3",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "20",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangViscachaTitularGordis",
		"size_rtl": "20",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangViscachaTitularGordis",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiTxtPreloadFont3",
		"type": "text"
	},
	{
		"string": "STR_LOADING_PRELOAD_FONT_4",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "20",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenial",
		"size_rtl": "20",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenial",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiTxtPreloadFont4",
		"type": "text"
	}
]);
